### ISSUE TITLE
It has cors issues, which another chrome extension does not

### ISSUE THREAD

**Issue by themarceldekoster** [jiayx/swagger-ui-chrome#2]
I cannot connect to localhost to test my swagger yaml file with this tool

**Comment by jiayx** [comment]
Thanks for the feedback, I'll test it.

**Comment by jiayx** [comment]
Fixed, wait for the chrome app store to approve the upgrade

**Comment by jiayx** [comment]
The new version is now available in the Google App Store. You need to enable the extension manually after the upgrade.


https://chrome.google.com/webstore/detail/swagger-ui/liacakmdhalagfjlfdofigfoiocghoej

**Comment by themarceldekoster** [comment]
This works well. Thank you!

**Comment by themarceldekoster** [comment]
I was responding too soon. It seems it does load the yaml, but trying to interact with it I still get CORS errors. On first click on a specific operation I get errors, invoking I see the CORS errros.

**Comment by themarceldekoster** [comment]
It seems to work perfectly now.

**Comment by jiayx** [comment]
Okay, I test is also good.
